# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\.qgis2\python\plugins\GPSTrackerPlugin\Ui_GPSTracker.ui'
#
# Created: Sat Mar 29 13:31:54 2014
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_GPSTracker(object):
    def setupUi(self, GPSTracker):
        GPSTracker.setObjectName(_fromUtf8("GPSTracker"))
        GPSTracker.resize(293, 595)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(self.dockWidgetContents)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setContentsMargins(0, 1, 0, 2)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.btnPosition = QtGui.QToolButton(self.frame)
        self.btnPosition.setMinimumSize(QtCore.QSize(44, 26))
        self.btnPosition.setStyleSheet(_fromUtf8("QToolButton {min-height: 24px; min-width: 42px; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton:checked{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}"))
        self.btnPosition.setCheckable(True)
        self.btnPosition.setObjectName(_fromUtf8("btnPosition"))
        self.horizontalLayout_9.addWidget(self.btnPosition)
        self.btnLayers = QtGui.QToolButton(self.frame)
        self.btnLayers.setMinimumSize(QtCore.QSize(44, 26))
        self.btnLayers.setStyleSheet(_fromUtf8("QToolButton {min-height: 24px; min-width: 42px; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton:checked{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}"))
        self.btnLayers.setCheckable(True)
        self.btnLayers.setObjectName(_fromUtf8("btnLayers"))
        self.horizontalLayout_9.addWidget(self.btnLayers)
        self.btnCalcPoint = QtGui.QToolButton(self.frame)
        self.btnCalcPoint.setMinimumSize(QtCore.QSize(44, 26))
        self.btnCalcPoint.setStyleSheet(_fromUtf8("QToolButton {min-height: 24px; min-width: 42px; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton:checked{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}"))
        self.btnCalcPoint.setText(_fromUtf8(""))
        self.btnCalcPoint.setCheckable(True)
        self.btnCalcPoint.setObjectName(_fromUtf8("btnCalcPoint"))
        self.horizontalLayout_9.addWidget(self.btnCalcPoint)
        self.btnOptions = QtGui.QToolButton(self.frame)
        self.btnOptions.setMinimumSize(QtCore.QSize(44, 26))
        self.btnOptions.setStyleSheet(_fromUtf8("QToolButton {min-height: 24px; min-width: 42px; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton:checked{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}"))
        self.btnOptions.setCheckable(True)
        self.btnOptions.setObjectName(_fromUtf8("btnOptions"))
        self.horizontalLayout_9.addWidget(self.btnOptions)
        spacerItem = QtGui.QSpacerItem(93, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.btnConnect = QtGui.QPushButton(self.frame)
        self.btnConnect.setMinimumSize(QtCore.QSize(0, 40))
        self.btnConnect.setCheckable(True)
        self.btnConnect.setObjectName(_fromUtf8("btnConnect"))
        self.horizontalLayout_9.addWidget(self.btnConnect)
        self.verticalLayout.addWidget(self.frame)
        self.stack = QtGui.QStackedWidget(self.dockWidgetContents)
        self.stack.setLineWidth(0)
        self.stack.setObjectName(_fromUtf8("stack"))
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.scrollArea_3 = QtGui.QScrollArea(self.page_2)
        self.scrollArea_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_3.setLineWidth(0)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 293, 530))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.gridLayout_11 = QtGui.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.vlInfoList = QtGui.QVBoxLayout()
        self.vlInfoList.setObjectName(_fromUtf8("vlInfoList"))
        self.gridLayout_11.addLayout(self.vlInfoList, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_4.addWidget(self.scrollArea_3)
        self.stack.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.scrollArea = QtGui.QScrollArea(self.page_3)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 170, 192))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_5 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setHorizontalSpacing(0)
        self.gridLayout_5.setVerticalSpacing(2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gbLayers = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbLayers.sizePolicy().hasHeightForWidth())
        self.gbLayers.setSizePolicy(sizePolicy)
        self.gbLayers.setObjectName(_fromUtf8("gbLayers"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gbLayers)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setContentsMargins(4, 2, 4, 2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cmbLayers = QtGui.QComboBox(self.gbLayers)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbLayers.sizePolicy().hasHeightForWidth())
        self.cmbLayers.setSizePolicy(sizePolicy)
        self.cmbLayers.setMinimumSize(QtCore.QSize(0, 26))
        self.cmbLayers.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.cmbLayers.setObjectName(_fromUtf8("cmbLayers"))
        self.gridLayout_2.addWidget(self.cmbLayers, 0, 1, 1, 2)
        self.btnAddFeatures = QtGui.QToolButton(self.gbLayers)
        self.btnAddFeatures.setMinimumSize(QtCore.QSize(64, 26))
        self.btnAddFeatures.setStyleSheet(_fromUtf8("QToolButton {min-width: 30; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton[popupMode=\"1\"] { padding-right: 32px; }\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton::menu-button{border: 1px solid gray; border-top-right-radius: 6px; border-bottom-right-radius: 6px; width: 30px; }\n"
"QToolButton::menu-arrow:open {top: 1px; left: 1px;}"))
        self.btnAddFeatures.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.btnAddFeatures.setObjectName(_fromUtf8("btnAddFeatures"))
        self.gridLayout_2.addWidget(self.btnAddFeatures, 0, 3, 1, 1)
        self.gridLayout_5.addWidget(self.gbLayers, 8, 0, 1, 1)
        self.btnSelection = QtGui.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelection.sizePolicy().hasHeightForWidth())
        self.btnSelection.setSizePolicy(sizePolicy)
        self.btnSelection.setMinimumSize(QtCore.QSize(64, 32))
        self.btnSelection.setStyleSheet(_fromUtf8("QToolButton {min-width: 30; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton[popupMode=\"1\"] { padding-right: 32px; }\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton::menu-button{border: 1px solid gray; border-top-right-radius: 6px; border-bottom-right-radius: 6px; width: 30px; }\n"
"QToolButton::menu-arrow:open {top: 1px; left: 1px;}"))
        self.btnSelection.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.btnSelection.setObjectName(_fromUtf8("btnSelection"))
        self.gridLayout_5.addWidget(self.btnSelection, 6, 0, 1, 1)
        self.vlPointList = QtGui.QVBoxLayout()
        self.vlPointList.setObjectName(_fromUtf8("vlPointList"))
        self.gridLayout_5.addLayout(self.vlPointList, 3, 0, 1, 1)
        self.cbDisplayPoints = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.cbDisplayPoints.setObjectName(_fromUtf8("cbDisplayPoints"))
        self.gridLayout_5.addWidget(self.cbDisplayPoints, 1, 0, 1, 1)
        self.btnMeasurePoint = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.btnMeasurePoint.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMeasurePoint.sizePolicy().hasHeightForWidth())
        self.btnMeasurePoint.setSizePolicy(sizePolicy)
        self.btnMeasurePoint.setMinimumSize(QtCore.QSize(64, 26))
        self.btnMeasurePoint.setStyleSheet(_fromUtf8("QToolButton {min-width: 30; min-height: 24; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton[popupMode=\"1\"] { padding-right: 32px; }\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton::menu-button{border: 1px solid gray; border-top-right-radius: 6px; border-bottom-right-radius: 6px; width: 30px; }\n"
"QToolButton::menu-arrow:open {top: 1px; left: 1px;}"))
        self.btnMeasurePoint.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.btnMeasurePoint.setObjectName(_fromUtf8("btnMeasurePoint"))
        self.gridLayout_5.addWidget(self.btnMeasurePoint, 4, 0, 1, 1)
        self.btnDeletePoint = QtGui.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDeletePoint.sizePolicy().hasHeightForWidth())
        self.btnDeletePoint.setSizePolicy(sizePolicy)
        self.btnDeletePoint.setMinimumSize(QtCore.QSize(64, 32))
        self.btnDeletePoint.setStyleSheet(_fromUtf8("QToolButton {min-width: 30; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton[popupMode=\"1\"] { padding-right: 32px; }\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton::menu-button{border: 1px solid gray; border-top-right-radius: 6px; border-bottom-right-radius: 6px; width: 30px; }\n"
"QToolButton::menu-arrow:open {top: 1px; left: 1px;}"))
        self.btnDeletePoint.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.btnDeletePoint.setObjectName(_fromUtf8("btnDeletePoint"))
        self.gridLayout_5.addWidget(self.btnDeletePoint, 7, 0, 1, 1)
        self.btnIntervalMeasure = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.btnIntervalMeasure.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnIntervalMeasure.sizePolicy().hasHeightForWidth())
        self.btnIntervalMeasure.setSizePolicy(sizePolicy)
        self.btnIntervalMeasure.setStyleSheet(_fromUtf8("QToolButton {min-height: 24px; min-width: 24px; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #33AD5C, stop: 1 #C2FFC2); border: 1px solid #1F6837}\n"
"QToolButton:checked{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #33AD5C, stop: 1 #C2FFC2); border: 1px solid #1F6837}"))
        self.btnIntervalMeasure.setCheckable(True)
        self.btnIntervalMeasure.setObjectName(_fromUtf8("btnIntervalMeasure"))
        self.gridLayout_5.addWidget(self.btnIntervalMeasure, 5, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 2, 0, 1, 1)
        self.stack.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_4)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.scrollArea_4 = QtGui.QScrollArea(self.page_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_4.sizePolicy().hasHeightForWidth())
        self.scrollArea_4.setSizePolicy(sizePolicy)
        self.scrollArea_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_4.setLineWidth(0)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName(_fromUtf8("scrollArea_4"))
        self.scrollAreaWidgetContents_4 = QtGui.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 157, 276))
        self.scrollAreaWidgetContents_4.setObjectName(_fromUtf8("scrollAreaWidgetContents_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_9.setMargin(2)
        self.gridLayout_9.setHorizontalSpacing(2)
        self.gridLayout_9.setVerticalSpacing(1)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnA = QtGui.QToolButton(self.groupBox)
        self.btnA.setMinimumSize(QtCore.QSize(64, 26))
        self.btnA.setStyleSheet(_fromUtf8("QToolButton {min-width: 30; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton[popupMode=\"1\"] { padding-right: 32px; }\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton:checked{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton::menu-button{border: 1px solid gray; border-top-right-radius: 6px; border-bottom-right-radius: 6px; width: 30px; }\n"
"QToolButton::menu-arrow:open {top: 1px; left: 1px;}"))
        self.btnA.setText(_fromUtf8(""))
        self.btnA.setCheckable(True)
        self.btnA.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.btnA.setObjectName(_fromUtf8("btnA"))
        self.horizontalLayout_5.addWidget(self.btnA)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lblAX = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAX.sizePolicy().hasHeightForWidth())
        self.lblAX.setSizePolicy(sizePolicy)
        self.lblAX.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.lblAX.setObjectName(_fromUtf8("lblAX"))
        self.horizontalLayout_5.addWidget(self.lblAX)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.lblAY = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAY.sizePolicy().hasHeightForWidth())
        self.lblAY.setSizePolicy(sizePolicy)
        self.lblAY.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.lblAY.setObjectName(_fromUtf8("lblAY"))
        self.horizontalLayout_5.addWidget(self.lblAY)
        self.gridLayout_9.addLayout(self.horizontalLayout_5, 0, 0, 1, 2)
        self.label_12 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_9.addWidget(self.label_12, 1, 0, 1, 1)
        self.sbAP = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbAP.sizePolicy().hasHeightForWidth())
        self.sbAP.setSizePolicy(sizePolicy)
        self.sbAP.setDecimals(2)
        self.sbAP.setMaximum(1000000.0)
        self.sbAP.setObjectName(_fromUtf8("sbAP"))
        self.gridLayout_9.addWidget(self.sbAP, 1, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_12.setMargin(2)
        self.gridLayout_12.setHorizontalSpacing(2)
        self.gridLayout_12.setVerticalSpacing(1)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btnB = QtGui.QToolButton(self.groupBox_4)
        self.btnB.setMinimumSize(QtCore.QSize(64, 26))
        self.btnB.setStyleSheet(_fromUtf8("QToolButton {min-width: 30; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton[popupMode=\"1\"] { padding-right: 32px; }\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton:checked{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton::menu-button{border: 1px solid gray; border-top-right-radius: 6px; border-bottom-right-radius: 6px; width: 30px; }\n"
"QToolButton::menu-arrow:open {top: 1px; left: 1px;}"))
        self.btnB.setText(_fromUtf8(""))
        self.btnB.setCheckable(True)
        self.btnB.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.btnB.setObjectName(_fromUtf8("btnB"))
        self.horizontalLayout_6.addWidget(self.btnB)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_6.addWidget(self.label_9)
        self.lblBX = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBX.sizePolicy().hasHeightForWidth())
        self.lblBX.setSizePolicy(sizePolicy)
        self.lblBX.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.lblBX.setObjectName(_fromUtf8("lblBX"))
        self.horizontalLayout_6.addWidget(self.lblBX)
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_6.addWidget(self.label_20)
        self.lblBY = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBY.sizePolicy().hasHeightForWidth())
        self.lblBY.setSizePolicy(sizePolicy)
        self.lblBY.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.lblBY.setObjectName(_fromUtf8("lblBY"))
        self.horizontalLayout_6.addWidget(self.lblBY)
        self.gridLayout_12.addLayout(self.horizontalLayout_6, 0, 0, 1, 2)
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_12.addWidget(self.label_13, 1, 0, 1, 1)
        self.sbBP = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.sbBP.setDecimals(2)
        self.sbBP.setMaximum(1000000.0)
        self.sbBP.setObjectName(_fromUtf8("sbBP"))
        self.gridLayout_12.addWidget(self.sbBP, 1, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.gbCalcPoint = QtGui.QGroupBox(self.scrollAreaWidgetContents_4)
        self.gbCalcPoint.setObjectName(_fromUtf8("gbCalcPoint"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.gbCalcPoint)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setMargin(2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_15 = QtGui.QLabel(self.gbCalcPoint)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setStyleSheet(_fromUtf8("color: rgb(0, 120, 0);"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_3.addWidget(self.label_15)
        self.lblYP = QtGui.QLabel(self.gbCalcPoint)
        self.lblYP.setStyleSheet(_fromUtf8("color: rgb(0, 120, 0);"))
        self.lblYP.setObjectName(_fromUtf8("lblYP"))
        self.horizontalLayout_3.addWidget(self.lblYP)
        self.label_16 = QtGui.QLabel(self.gbCalcPoint)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setStyleSheet(_fromUtf8("color: rgb(0, 120, 0);"))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_3.addWidget(self.label_16)
        self.lblXP = QtGui.QLabel(self.gbCalcPoint)
        self.lblXP.setStyleSheet(_fromUtf8("color: rgb(0, 120, 0);"))
        self.lblXP.setObjectName(_fromUtf8("lblXP"))
        self.horizontalLayout_3.addWidget(self.lblXP)
        self.verticalLayout_6.addWidget(self.gbCalcPoint)
        self.bAddCalcPoint = QtGui.QToolButton(self.scrollAreaWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bAddCalcPoint.sizePolicy().hasHeightForWidth())
        self.bAddCalcPoint.setSizePolicy(sizePolicy)
        self.bAddCalcPoint.setMinimumSize(QtCore.QSize(32, 32))
        self.bAddCalcPoint.setStyleSheet(_fromUtf8("QToolButton {min-width: 30; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton[popupMode=\"1\"] { padding-right: 32px; }\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton::menu-button{border: 1px solid gray; border-top-right-radius: 6px; border-bottom-right-radius: 6px; width: 30px; }\n"
"QToolButton::menu-arrow:open {top: 1px; left: 1px;}"))
        self.bAddCalcPoint.setObjectName(_fromUtf8("bAddCalcPoint"))
        self.verticalLayout_6.addWidget(self.bAddCalcPoint)
        self.bClear = QtGui.QToolButton(self.scrollAreaWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bClear.sizePolicy().hasHeightForWidth())
        self.bClear.setSizePolicy(sizePolicy)
        self.bClear.setMinimumSize(QtCore.QSize(32, 32))
        self.bClear.setStyleSheet(_fromUtf8("QToolButton {min-width: 30; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton[popupMode=\"1\"] { padding-right: 32px; }\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton::menu-button{border: 1px solid gray; border-top-right-radius: 6px; border-bottom-right-radius: 6px; width: 30px; }\n"
"QToolButton::menu-arrow:open {top: 1px; left: 1px;}"))
        self.bClear.setObjectName(_fromUtf8("bClear"))
        self.verticalLayout_6.addWidget(self.bClear)
        self.bReplace = QtGui.QToolButton(self.scrollAreaWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bReplace.sizePolicy().hasHeightForWidth())
        self.bReplace.setSizePolicy(sizePolicy)
        self.bReplace.setMinimumSize(QtCore.QSize(32, 32))
        self.bReplace.setStyleSheet(_fromUtf8("QToolButton {min-width: 30; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton[popupMode=\"1\"] { padding-right: 32px; }\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton::menu-button{border: 1px solid gray; border-top-right-radius: 6px; border-bottom-right-radius: 6px; width: 30px; }\n"
"QToolButton::menu-arrow:open {top: 1px; left: 1px;}"))
        self.bReplace.setObjectName(_fromUtf8("bReplace"))
        self.verticalLayout_6.addWidget(self.bReplace)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_5.addWidget(self.scrollArea_4)
        self.stack.addWidget(self.page_4)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_7 = QtGui.QGridLayout(self.page)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.scrollArea_2 = QtGui.QScrollArea(self.page)
        self.scrollArea_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_2.setLineWidth(0)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 293, 530))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblCRS = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCRS.sizePolicy().hasHeightForWidth())
        self.lblCRS.setSizePolicy(sizePolicy)
        self.lblCRS.setObjectName(_fromUtf8("lblCRS"))
        self.horizontalLayout_2.addWidget(self.lblCRS)
        self.cmbCRS = QtGui.QComboBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCRS.sizePolicy().hasHeightForWidth())
        self.cmbCRS.setSizePolicy(sizePolicy)
        self.cmbCRS.setMinimumSize(QtCore.QSize(0, 26))
        self.cmbCRS.setObjectName(_fromUtf8("cmbCRS"))
        self.cmbCRS.addItem(_fromUtf8(""))
        self.cmbCRS.addItem(_fromUtf8(""))
        self.cmbCRS.addItem(_fromUtf8(""))
        self.cmbCRS.addItem(_fromUtf8(""))
        self.cmbCRS.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.cmbCRS)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.cmbPorts = QtGui.QComboBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPorts.sizePolicy().hasHeightForWidth())
        self.cmbPorts.setSizePolicy(sizePolicy)
        self.cmbPorts.setMinimumSize(QtCore.QSize(0, 26))
        self.cmbPorts.setObjectName(_fromUtf8("cmbPorts"))
        self.horizontalLayout_8.addWidget(self.cmbPorts)
        self.btnPorts = QtGui.QToolButton(self.scrollAreaWidgetContents_2)
        self.btnPorts.setMinimumSize(QtCore.QSize(26, 26))
        self.btnPorts.setObjectName(_fromUtf8("btnPorts"))
        self.horizontalLayout_8.addWidget(self.btnPorts)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.gbPointAddMode = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.gbPointAddMode.setEnabled(True)
        self.gbPointAddMode.setObjectName(_fromUtf8("gbPointAddMode"))
        self.gridLayout = QtGui.QGridLayout(self.gbPointAddMode)
        self.gridLayout.setContentsMargins(4, 2, 4, 2)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.rbTimeAverage = QtGui.QRadioButton(self.gbPointAddMode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbTimeAverage.sizePolicy().hasHeightForWidth())
        self.rbTimeAverage.setSizePolicy(sizePolicy)
        self.rbTimeAverage.setChecked(True)
        self.rbTimeAverage.setObjectName(_fromUtf8("rbTimeAverage"))
        self.gridLayout.addWidget(self.rbTimeAverage, 0, 0, 1, 1)
        self.sbMeasureCount = QtGui.QSpinBox(self.gbPointAddMode)
        self.sbMeasureCount.setMinimum(1)
        self.sbMeasureCount.setMaximum(9999)
        self.sbMeasureCount.setProperty(_fromUtf8("value"), 5)
        self.sbMeasureCount.setObjectName(_fromUtf8("sbMeasureCount"))
        self.gridLayout.addWidget(self.sbMeasureCount, 0, 2, 1, 1)
        self.rbShotsAverage = QtGui.QRadioButton(self.gbPointAddMode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbShotsAverage.sizePolicy().hasHeightForWidth())
        self.rbShotsAverage.setSizePolicy(sizePolicy)
        self.rbShotsAverage.setObjectName(_fromUtf8("rbShotsAverage"))
        self.gridLayout.addWidget(self.rbShotsAverage, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.gbPointAddMode)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2)
        self.sbMeasureDistance = QtGui.QSpinBox(self.gbPointAddMode)
        self.sbMeasureDistance.setMinimum(1)
        self.sbMeasureDistance.setMaximum(999)
        self.sbMeasureDistance.setProperty(_fromUtf8("value"), 25)
        self.sbMeasureDistance.setObjectName(_fromUtf8("sbMeasureDistance"))
        self.gridLayout.addWidget(self.sbMeasureDistance, 1, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.gbPointAddMode)
        self.gbMarker = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.gbMarker.setCheckable(True)
        self.gbMarker.setObjectName(_fromUtf8("gbMarker"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gbMarker)
        self.gridLayout_6.setMargin(2)
        self.gridLayout_6.setHorizontalSpacing(2)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_5 = QtGui.QLabel(self.gbMarker)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.cmbMarker = QtGui.QComboBox(self.gbMarker)
        self.cmbMarker.setObjectName(_fromUtf8("cmbMarker"))
        self.gridLayout_6.addWidget(self.cmbMarker, 0, 1, 1, 2)
        self.label_7 = QtGui.QLabel(self.gbMarker)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 2, 0, 1, 1)
        self.sMarkerSize = QtGui.QSlider(self.gbMarker)
        self.sMarkerSize.setMinimum(8)
        self.sMarkerSize.setMaximum(128)
        self.sMarkerSize.setSingleStep(4)
        self.sMarkerSize.setPageStep(8)
        self.sMarkerSize.setSliderPosition(24)
        self.sMarkerSize.setOrientation(QtCore.Qt.Horizontal)
        self.sMarkerSize.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sMarkerSize.setTickInterval(8)
        self.sMarkerSize.setObjectName(_fromUtf8("sMarkerSize"))
        self.gridLayout_6.addWidget(self.sMarkerSize, 2, 1, 1, 1)
        self.sbMarkerSize = QtGui.QSpinBox(self.gbMarker)
        self.sbMarkerSize.setMinimum(8)
        self.sbMarkerSize.setMaximum(128)
        self.sbMarkerSize.setProperty(_fromUtf8("value"), 24)
        self.sbMarkerSize.setObjectName(_fromUtf8("sbMarkerSize"))
        self.gridLayout_6.addWidget(self.sbMarkerSize, 2, 2, 1, 1)
        self.lblMarker = QtGui.QLabel(self.gbMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMarker.sizePolicy().hasHeightForWidth())
        self.lblMarker.setSizePolicy(sizePolicy)
        self.lblMarker.setMaximumSize(QtCore.QSize(16777215, 130))
        self.lblMarker.setFrameShape(QtGui.QFrame.Box)
        self.lblMarker.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblMarker.setText(_fromUtf8(""))
        self.lblMarker.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMarker.setMargin(2)
        self.lblMarker.setObjectName(_fromUtf8("lblMarker"))
        self.gridLayout_6.addWidget(self.lblMarker, 1, 0, 1, 3)
        self.verticalLayout_3.addWidget(self.gbMarker)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setMargin(2)
        self.gridLayout_8.setHorizontalSpacing(2)
        self.gridLayout_8.setVerticalSpacing(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.sbExt = QtGui.QSpinBox(self.groupBox_2)
        self.sbExt.setEnabled(False)
        self.sbExt.setMinimum(5)
        self.sbExt.setMaximum(100)
        self.sbExt.setProperty(_fromUtf8("value"), 50)
        self.sbExt.setObjectName(_fromUtf8("sbExt"))
        self.gridLayout_8.addWidget(self.sbExt, 1, 0, 1, 2)
        self.cmbCenter = QtGui.QComboBox(self.groupBox_2)
        self.cmbCenter.setObjectName(_fromUtf8("cmbCenter"))
        self.cmbCenter.addItem(_fromUtf8(""))
        self.cmbCenter.addItem(_fromUtf8(""))
        self.cmbCenter.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.cmbCenter, 0, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.gbLogDir = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.gbLogDir.setObjectName(_fromUtf8("gbLogDir"))
        self.gridLayout_13 = QtGui.QGridLayout(self.gbLogDir)
        self.gridLayout_13.setMargin(2)
        self.gridLayout_13.setHorizontalSpacing(2)
        self.gridLayout_13.setVerticalSpacing(1)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.eLogDir = QtGui.QLineEdit(self.gbLogDir)
        self.eLogDir.setMinimumSize(QtCore.QSize(0, 26))
        self.eLogDir.setObjectName(_fromUtf8("eLogDir"))
        self.gridLayout_13.addWidget(self.eLogDir, 0, 1, 1, 1)
        self.cbLogGPS = QtGui.QCheckBox(self.gbLogDir)
        self.cbLogGPS.setObjectName(_fromUtf8("cbLogGPS"))
        self.gridLayout_13.addWidget(self.cbLogGPS, 1, 1, 1, 2)
        self.btnChangeLogDir = QtGui.QToolButton(self.gbLogDir)
        self.btnChangeLogDir.setMinimumSize(QtCore.QSize(64, 26))
        self.btnChangeLogDir.setStyleSheet(_fromUtf8("QToolButton {min-width: 30; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton[popupMode=\"1\"] { padding-right: 32px; }\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton::menu-button{border: 1px solid gray; border-top-right-radius: 6px; border-bottom-right-radius: 6px; width: 30px; }\n"
"QToolButton::menu-arrow:open {top: 1px; left: 1px;}"))
        self.btnChangeLogDir.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.btnChangeLogDir.setObjectName(_fromUtf8("btnChangeLogDir"))
        self.gridLayout_13.addWidget(self.btnChangeLogDir, 0, 2, 1, 1)
        self.cbSaveMeasure = QtGui.QCheckBox(self.gbLogDir)
        self.cbSaveMeasure.setChecked(True)
        self.cbSaveMeasure.setObjectName(_fromUtf8("cbSaveMeasure"))
        self.gridLayout_13.addWidget(self.cbSaveMeasure, 2, 1, 1, 1)
        self.sbMesaureSaveTime = QtGui.QSpinBox(self.gbLogDir)
        self.sbMesaureSaveTime.setMinimum(1)
        self.sbMesaureSaveTime.setObjectName(_fromUtf8("sbMesaureSaveTime"))
        self.gridLayout_13.addWidget(self.sbMesaureSaveTime, 2, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.gbLogDir)
        self.gbPointDistance = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.gbPointDistance.setCheckable(True)
        self.gbPointDistance.setChecked(False)
        self.gbPointDistance.setObjectName(_fromUtf8("gbPointDistance"))
        self.gridLayout_10 = QtGui.QGridLayout(self.gbPointDistance)
        self.gridLayout_10.setMargin(2)
        self.gridLayout_10.setHorizontalSpacing(2)
        self.gridLayout_10.setVerticalSpacing(1)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_18 = QtGui.QLabel(self.gbPointDistance)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_10.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.gbPointDistance)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_10.addWidget(self.label_17, 2, 0, 1, 1)
        self.cmbFontSizes = QtGui.QComboBox(self.gbPointDistance)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFontSizes.sizePolicy().hasHeightForWidth())
        self.cmbFontSizes.setSizePolicy(sizePolicy)
        self.cmbFontSizes.setObjectName(_fromUtf8("cmbFontSizes"))
        self.gridLayout_10.addWidget(self.cmbFontSizes, 2, 1, 1, 2)
        self.lblSampleText = QtGui.QLabel(self.gbPointDistance)
        self.lblSampleText.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lblSampleText.setFont(font)
        self.lblSampleText.setFrameShape(QtGui.QFrame.Panel)
        self.lblSampleText.setFrameShadow(QtGui.QFrame.Sunken)
        self.lblSampleText.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSampleText.setObjectName(_fromUtf8("lblSampleText"))
        self.gridLayout_10.addWidget(self.lblSampleText, 4, 0, 1, 3)
        self.label_19 = QtGui.QLabel(self.gbPointDistance)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_10.addWidget(self.label_19, 3, 0, 1, 1)
        self.btnFontColor = QtGui.QPushButton(self.gbPointDistance)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFontColor.sizePolicy().hasHeightForWidth())
        self.btnFontColor.setSizePolicy(sizePolicy)
        self.btnFontColor.setObjectName(_fromUtf8("btnFontColor"))
        self.gridLayout_10.addWidget(self.btnFontColor, 3, 1, 1, 2)
        self.cmbFonts = QtGui.QFontComboBox(self.gbPointDistance)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFonts.sizePolicy().hasHeightForWidth())
        self.cmbFonts.setSizePolicy(sizePolicy)
        self.cmbFonts.setEditable(False)
        self.cmbFonts.setFontFilters(QtGui.QFontComboBox.ScalableFonts)
        self.cmbFonts.setObjectName(_fromUtf8("cmbFonts"))
        self.gridLayout_10.addWidget(self.cmbFonts, 1, 1, 1, 2)
        self.verticalLayout_3.addWidget(self.gbPointDistance)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setMargin(2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.sWidgetsSize = QtGui.QSlider(self.groupBox_3)
        self.sWidgetsSize.setMinimum(8)
        self.sWidgetsSize.setMaximum(48)
        self.sWidgetsSize.setSingleStep(4)
        self.sWidgetsSize.setPageStep(8)
        self.sWidgetsSize.setProperty(_fromUtf8("value"), 20)
        self.sWidgetsSize.setSliderPosition(20)
        self.sWidgetsSize.setOrientation(QtCore.Qt.Horizontal)
        self.sWidgetsSize.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sWidgetsSize.setTickInterval(8)
        self.sWidgetsSize.setObjectName(_fromUtf8("sWidgetsSize"))
        self.horizontalLayout.addWidget(self.sWidgetsSize)
        self.sbWidgetsSize = QtGui.QSpinBox(self.groupBox_3)
        self.sbWidgetsSize.setMinimum(8)
        self.sbWidgetsSize.setMaximum(48)
        self.sbWidgetsSize.setProperty(_fromUtf8("value"), 20)
        self.sbWidgetsSize.setObjectName(_fromUtf8("sbWidgetsSize"))
        self.horizontalLayout.addWidget(self.sbWidgetsSize)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_7.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.stack.addWidget(self.page)
        self.verticalLayout.addWidget(self.stack)
        GPSTracker.setWidget(self.dockWidgetContents)

        self.retranslateUi(GPSTracker)
        self.stack.setCurrentIndex(0)
        self.cmbCRS.setCurrentIndex(4)
        QtCore.QObject.connect(self.sMarkerSize, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.sbMarkerSize.setValue)
        QtCore.QObject.connect(self.sbMarkerSize, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.sMarkerSize.setValue)
        QtCore.QObject.connect(self.sWidgetsSize, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.sbWidgetsSize.setValue)
        QtCore.QObject.connect(self.sbWidgetsSize, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.sWidgetsSize.setValue)
        QtCore.QMetaObject.connectSlotsByName(GPSTracker)
        GPSTracker.setTabOrder(self.cmbCRS, self.scrollArea_3)
        GPSTracker.setTabOrder(self.scrollArea_3, self.scrollArea)
        GPSTracker.setTabOrder(self.scrollArea, self.cmbLayers)
        GPSTracker.setTabOrder(self.cmbLayers, self.scrollArea_2)
        GPSTracker.setTabOrder(self.scrollArea_2, self.gbMarker)
        GPSTracker.setTabOrder(self.gbMarker, self.cmbMarker)
        GPSTracker.setTabOrder(self.cmbMarker, self.sMarkerSize)
        GPSTracker.setTabOrder(self.sMarkerSize, self.sbMarkerSize)
        GPSTracker.setTabOrder(self.sbMarkerSize, self.sbExt)
        GPSTracker.setTabOrder(self.sbExt, self.gbPointDistance)
        GPSTracker.setTabOrder(self.gbPointDistance, self.cmbFonts)
        GPSTracker.setTabOrder(self.cmbFonts, self.cmbFontSizes)
        GPSTracker.setTabOrder(self.cmbFontSizes, self.btnFontColor)

    def retranslateUi(self, GPSTracker):
        GPSTracker.setWindowTitle(QtGui.QApplication.translate("GPSTracker", "GPS Tracker", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPosition.setToolTip(QtGui.QApplication.translate("GPSTracker", "Położenie", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLayers.setToolTip(QtGui.QApplication.translate("GPSTracker", "Rejestracja punktów", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCalcPoint.setToolTip(QtGui.QApplication.translate("GPSTracker", "Wcięcie liniowe w przód", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOptions.setToolTip(QtGui.QApplication.translate("GPSTracker", "Ustawienia", None, QtGui.QApplication.UnicodeUTF8))
        self.btnConnect.setToolTip(QtGui.QApplication.translate("GPSTracker", "Połączenie z odbiornikiem GPS", None, QtGui.QApplication.UnicodeUTF8))
        self.btnConnect.setText(QtGui.QApplication.translate("GPSTracker", "Połącz", None, QtGui.QApplication.UnicodeUTF8))
        self.gbLayers.setTitle(QtGui.QApplication.translate("GPSTracker", "Zapis obiektów", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddFeatures.setText(QtGui.QApplication.translate("GPSTracker", "Zap. wsz. pkt", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSelection.setText(QtGui.QApplication.translate("GPSTracker", "Zaznacz wszystkie", None, QtGui.QApplication.UnicodeUTF8))
        self.cbDisplayPoints.setText(QtGui.QApplication.translate("GPSTracker", "Wyświetl punkty w oknie mapy", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMeasurePoint.setText(QtGui.QApplication.translate("GPSTracker", "Nowy pomiar", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDeletePoint.setText(QtGui.QApplication.translate("GPSTracker", "Usuń wybrany", None, QtGui.QApplication.UnicodeUTF8))
        self.btnIntervalMeasure.setText(QtGui.QApplication.translate("GPSTracker", "Automatyczny\n"
"pomiar co 25 m", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("GPSTracker", "Punkt lewy A", None, QtGui.QApplication.UnicodeUTF8))
        self.btnA.setAccessibleDescription(QtGui.QApplication.translate("GPSTracker", "left", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("GPSTracker", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAX.setText(QtGui.QApplication.translate("GPSTracker", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("GPSTracker", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAY.setText(QtGui.QApplication.translate("GPSTracker", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("GPSTracker", "Odległość AP:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("GPSTracker", "Punkt prawy B", None, QtGui.QApplication.UnicodeUTF8))
        self.btnB.setAccessibleDescription(QtGui.QApplication.translate("GPSTracker", "right", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("GPSTracker", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBX.setText(QtGui.QApplication.translate("GPSTracker", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("GPSTracker", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBY.setText(QtGui.QApplication.translate("GPSTracker", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("GPSTracker", "Odległość BP:", None, QtGui.QApplication.UnicodeUTF8))
        self.gbCalcPoint.setTitle(QtGui.QApplication.translate("GPSTracker", "Szukany punkt P", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("GPSTracker", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblYP.setText(QtGui.QApplication.translate("GPSTracker", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("GPSTracker", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblXP.setText(QtGui.QApplication.translate("GPSTracker", "N/A", None, QtGui.QApplication.UnicodeUTF8))
        self.bAddCalcPoint.setToolTip(QtGui.QApplication.translate("GPSTracker", "Dodaj punkt P do listy", None, QtGui.QApplication.UnicodeUTF8))
        self.bAddCalcPoint.setText(QtGui.QApplication.translate("GPSTracker", "Dodaj punkt", None, QtGui.QApplication.UnicodeUTF8))
        self.bClear.setToolTip(QtGui.QApplication.translate("GPSTracker", "Zresetuj wprowadzone dane", None, QtGui.QApplication.UnicodeUTF8))
        self.bClear.setText(QtGui.QApplication.translate("GPSTracker", "Wyczyść dane", None, QtGui.QApplication.UnicodeUTF8))
        self.bReplace.setToolTip(QtGui.QApplication.translate("GPSTracker", "Zamień współrzędne punktów A i B", None, QtGui.QApplication.UnicodeUTF8))
        self.bReplace.setText(QtGui.QApplication.translate("GPSTracker", "Zamień punkt A i B", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCRS.setText(QtGui.QApplication.translate("GPSTracker", "PUWG:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbCRS.setToolTip(QtGui.QApplication.translate("GPSTracker", "Układ współrzędnych w jakim wyświetlane są koordynaty punktów", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbCRS.setItemText(0, QtGui.QApplication.translate("GPSTracker", "2000 Strefa 5", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbCRS.setItemText(1, QtGui.QApplication.translate("GPSTracker", "2000 Strefa 6", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbCRS.setItemText(2, QtGui.QApplication.translate("GPSTracker", "2000 Strefa 7", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbCRS.setItemText(3, QtGui.QApplication.translate("GPSTracker", "2000 Strefa 8", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbCRS.setItemText(4, QtGui.QApplication.translate("GPSTracker", "1992", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("GPSTracker", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbPorts.setToolTip(QtGui.QApplication.translate("GPSTracker", "Nazwa portu, do którego podłączony jest odbiornik GPS", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPorts.setToolTip(QtGui.QApplication.translate("GPSTracker", "Odśwież listę portów", None, QtGui.QApplication.UnicodeUTF8))
        self.gbPointAddMode.setTitle(QtGui.QApplication.translate("GPSTracker", "Rejestracja punktów", None, QtGui.QApplication.UnicodeUTF8))
        self.rbTimeAverage.setToolTip(QtGui.QApplication.translate("GPSTracker", "Średni pomiar w określonym czasie", None, QtGui.QApplication.UnicodeUTF8))
        self.rbTimeAverage.setText(QtGui.QApplication.translate("GPSTracker", "Sek. /", None, QtGui.QApplication.UnicodeUTF8))
        self.rbShotsAverage.setToolTip(QtGui.QApplication.translate("GPSTracker", "Średnia z określonej liczby pomiarów", None, QtGui.QApplication.UnicodeUTF8))
        self.rbShotsAverage.setText(QtGui.QApplication.translate("GPSTracker", "L.pom.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("GPSTracker", "Odległość dla aut.pom.", None, QtGui.QApplication.UnicodeUTF8))
        self.sbMeasureDistance.setSuffix(QtGui.QApplication.translate("GPSTracker", " m", None, QtGui.QApplication.UnicodeUTF8))
        self.gbMarker.setTitle(QtGui.QApplication.translate("GPSTracker", "Wskaźnik", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("GPSTracker", "Plik ikony:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("GPSTracker", "Rozmiar:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("GPSTracker", "Centrowanie mapy", None, QtGui.QApplication.UnicodeUTF8))
        self.sbExt.setSuffix(QtGui.QApplication.translate("GPSTracker", "% zasięgu mapy", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbCenter.setItemText(0, QtGui.QApplication.translate("GPSTracker", "zawsze", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbCenter.setItemText(1, QtGui.QApplication.translate("GPSTracker", "nigdy", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbCenter.setItemText(2, QtGui.QApplication.translate("GPSTracker", "przy wychodzeniu...", None, QtGui.QApplication.UnicodeUTF8))
        self.gbLogDir.setTitle(QtGui.QApplication.translate("GPSTracker", "Katalog logowania", None, QtGui.QApplication.UnicodeUTF8))
        self.cbLogGPS.setText(QtGui.QApplication.translate("GPSTracker", "Zapisuj informacje z GPS w formacie NMEA", None, QtGui.QApplication.UnicodeUTF8))
        self.btnChangeLogDir.setText(QtGui.QApplication.translate("GPSTracker", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.cbSaveMeasure.setText(QtGui.QApplication.translate("GPSTracker", "Automatyczny zapis pomiarów:", None, QtGui.QApplication.UnicodeUTF8))
        self.sbMesaureSaveTime.setSuffix(QtGui.QApplication.translate("GPSTracker", " min", None, QtGui.QApplication.UnicodeUTF8))
        self.gbPointDistance.setTitle(QtGui.QApplication.translate("GPSTracker", "Odległość od punktu", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("GPSTracker", "Czcionka:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("GPSTracker", "Rozmiar:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSampleText.setText(QtGui.QApplication.translate("GPSTracker", "123.45", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("GPSTracker", "Kolor:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("GPSTracker", "Rozmiar przycisków", None, QtGui.QApplication.UnicodeUTF8))

