# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_GPSTracker.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GPSTracker(object):
    def setupUi(self, GPSTracker):
        GPSTracker.setObjectName("GPSTracker")
        GPSTracker.resize(293, 595)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.dockWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_9.setContentsMargins(0, 1, 0, 2)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btnPosition = QtWidgets.QToolButton(self.frame)
        self.btnPosition.setMinimumSize(QtCore.QSize(44, 26))
        self.btnPosition.setStyleSheet("QToolButton {min-height: 24px; min-width: 42px; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton:checked{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}")
        self.btnPosition.setCheckable(True)
        self.btnPosition.setObjectName("btnPosition")
        self.horizontalLayout_9.addWidget(self.btnPosition)
        self.btnLayers = QtWidgets.QToolButton(self.frame)
        self.btnLayers.setMinimumSize(QtCore.QSize(44, 26))
        self.btnLayers.setStyleSheet("QToolButton {min-height: 24px; min-width: 42px; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton:checked{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}")
        self.btnLayers.setCheckable(True)
        self.btnLayers.setObjectName("btnLayers")
        self.horizontalLayout_9.addWidget(self.btnLayers)
        self.btnCalcPoint = QtWidgets.QToolButton(self.frame)
        self.btnCalcPoint.setMinimumSize(QtCore.QSize(44, 26))
        self.btnCalcPoint.setStyleSheet("QToolButton {min-height: 24px; min-width: 42px; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton:checked{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}")
        self.btnCalcPoint.setText("")
        self.btnCalcPoint.setCheckable(True)
        self.btnCalcPoint.setObjectName("btnCalcPoint")
        self.horizontalLayout_9.addWidget(self.btnCalcPoint)
        self.btnOptions = QtWidgets.QToolButton(self.frame)
        self.btnOptions.setMinimumSize(QtCore.QSize(44, 26))
        self.btnOptions.setStyleSheet("QToolButton {min-height: 24px; min-width: 42px; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton:checked{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}")
        self.btnOptions.setCheckable(True)
        self.btnOptions.setObjectName("btnOptions")
        self.horizontalLayout_9.addWidget(self.btnOptions)
        spacerItem = QtWidgets.QSpacerItem(93, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.btnConnect = QtWidgets.QPushButton(self.frame)
        self.btnConnect.setMinimumSize(QtCore.QSize(0, 40))
        self.btnConnect.setCheckable(True)
        self.btnConnect.setObjectName("btnConnect")
        self.horizontalLayout_9.addWidget(self.btnConnect)
        self.verticalLayout.addWidget(self.frame)
        self.stack = QtWidgets.QStackedWidget(self.dockWidgetContents)
        self.stack.setLineWidth(0)
        self.stack.setObjectName("stack")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_3.setLineWidth(0)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.vlInfoList = QtWidgets.QVBoxLayout()
        self.vlInfoList.setObjectName("vlInfoList")
        self.gridLayout_11.addLayout(self.vlInfoList, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_4.addWidget(self.scrollArea_3)
        self.stack.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.page_3)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 170, 192))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(0)
        self.gridLayout_5.setVerticalSpacing(2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gbLayers = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbLayers.sizePolicy().hasHeightForWidth())
        self.gbLayers.setSizePolicy(sizePolicy)
        self.gbLayers.setObjectName("gbLayers")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbLayers)
        self.gridLayout_2.setContentsMargins(4, 2, 4, 2)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cmbLayers = QtWidgets.QComboBox(self.gbLayers)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbLayers.sizePolicy().hasHeightForWidth())
        self.cmbLayers.setSizePolicy(sizePolicy)
        self.cmbLayers.setMinimumSize(QtCore.QSize(0, 26))
        self.cmbLayers.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.cmbLayers.setObjectName("cmbLayers")
        self.gridLayout_2.addWidget(self.cmbLayers, 0, 1, 1, 2)
        self.btnAddFeatures = QtWidgets.QToolButton(self.gbLayers)
        self.btnAddFeatures.setMinimumSize(QtCore.QSize(64, 26))
        self.btnAddFeatures.setStyleSheet("QToolButton {min-width: 30; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton[popupMode=\"1\"] { padding-right: 32px; }\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton::menu-button{border: 1px solid gray; border-top-right-radius: 6px; border-bottom-right-radius: 6px; width: 30px; }\n"
"QToolButton::menu-arrow:open {top: 1px; left: 1px;}")
        self.btnAddFeatures.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.btnAddFeatures.setObjectName("btnAddFeatures")
        self.gridLayout_2.addWidget(self.btnAddFeatures, 0, 3, 1, 1)
        self.gridLayout_5.addWidget(self.gbLayers, 8, 0, 1, 1)
        self.btnSelection = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSelection.sizePolicy().hasHeightForWidth())
        self.btnSelection.setSizePolicy(sizePolicy)
        self.btnSelection.setMinimumSize(QtCore.QSize(64, 32))
        self.btnSelection.setStyleSheet("QToolButton {min-width: 30; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton[popupMode=\"1\"] { padding-right: 32px; }\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton::menu-button{border: 1px solid gray; border-top-right-radius: 6px; border-bottom-right-radius: 6px; width: 30px; }\n"
"QToolButton::menu-arrow:open {top: 1px; left: 1px;}")
        self.btnSelection.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.btnSelection.setObjectName("btnSelection")
        self.gridLayout_5.addWidget(self.btnSelection, 6, 0, 1, 1)
        self.vlPointList = QtWidgets.QVBoxLayout()
        self.vlPointList.setObjectName("vlPointList")
        self.gridLayout_5.addLayout(self.vlPointList, 3, 0, 1, 1)
        self.cbDisplayPoints = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.cbDisplayPoints.setObjectName("cbDisplayPoints")
        self.gridLayout_5.addWidget(self.cbDisplayPoints, 1, 0, 1, 1)
        self.btnMeasurePoint = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.btnMeasurePoint.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMeasurePoint.sizePolicy().hasHeightForWidth())
        self.btnMeasurePoint.setSizePolicy(sizePolicy)
        self.btnMeasurePoint.setMinimumSize(QtCore.QSize(64, 26))
        self.btnMeasurePoint.setStyleSheet("QToolButton {min-width: 30; min-height: 24; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton[popupMode=\"1\"] { padding-right: 32px; }\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton::menu-button{border: 1px solid gray; border-top-right-radius: 6px; border-bottom-right-radius: 6px; width: 30px; }\n"
"QToolButton::menu-arrow:open {top: 1px; left: 1px;}")
        self.btnMeasurePoint.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.btnMeasurePoint.setObjectName("btnMeasurePoint")
        self.gridLayout_5.addWidget(self.btnMeasurePoint, 4, 0, 1, 1)
        self.btnDeletePoint = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDeletePoint.sizePolicy().hasHeightForWidth())
        self.btnDeletePoint.setSizePolicy(sizePolicy)
        self.btnDeletePoint.setMinimumSize(QtCore.QSize(64, 32))
        self.btnDeletePoint.setStyleSheet("QToolButton {min-width: 30; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton[popupMode=\"1\"] { padding-right: 32px; }\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton::menu-button{border: 1px solid gray; border-top-right-radius: 6px; border-bottom-right-radius: 6px; width: 30px; }\n"
"QToolButton::menu-arrow:open {top: 1px; left: 1px;}")
        self.btnDeletePoint.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.btnDeletePoint.setObjectName("btnDeletePoint")
        self.gridLayout_5.addWidget(self.btnDeletePoint, 7, 0, 1, 1)
        self.btnIntervalMeasure = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.btnIntervalMeasure.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnIntervalMeasure.sizePolicy().hasHeightForWidth())
        self.btnIntervalMeasure.setSizePolicy(sizePolicy)
        self.btnIntervalMeasure.setStyleSheet("QToolButton {min-height: 24px; min-width: 24px; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #33AD5C, stop: 1 #C2FFC2); border: 1px solid #1F6837}\n"
"QToolButton:checked{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #33AD5C, stop: 1 #C2FFC2); border: 1px solid #1F6837}")
        self.btnIntervalMeasure.setCheckable(True)
        self.btnIntervalMeasure.setObjectName("btnIntervalMeasure")
        self.gridLayout_5.addWidget(self.btnIntervalMeasure, 5, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 2, 0, 1, 1)
        self.stack.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_4.sizePolicy().hasHeightForWidth())
        self.scrollArea_4.setSizePolicy(sizePolicy)
        self.scrollArea_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_4.setLineWidth(0)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 293, 530))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_9.setHorizontalSpacing(2)
        self.gridLayout_9.setVerticalSpacing(1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnA = QtWidgets.QToolButton(self.groupBox)
        self.btnA.setMinimumSize(QtCore.QSize(64, 26))
        self.btnA.setStyleSheet("QToolButton {min-width: 30; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton[popupMode=\"1\"] { padding-right: 32px; }\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton:checked{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton::menu-button{border: 1px solid gray; border-top-right-radius: 6px; border-bottom-right-radius: 6px; width: 30px; }\n"
"QToolButton::menu-arrow:open {top: 1px; left: 1px;}")
        self.btnA.setText("")
        self.btnA.setCheckable(True)
        self.btnA.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.btnA.setObjectName("btnA")
        self.horizontalLayout_5.addWidget(self.btnA)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lblAX = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAX.sizePolicy().hasHeightForWidth())
        self.lblAX.setSizePolicy(sizePolicy)
        self.lblAX.setStyleSheet("color: rgb(255, 0, 0);")
        self.lblAX.setObjectName("lblAX")
        self.horizontalLayout_5.addWidget(self.lblAX)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.lblAY = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAY.sizePolicy().hasHeightForWidth())
        self.lblAY.setSizePolicy(sizePolicy)
        self.lblAY.setStyleSheet("color: rgb(255, 0, 0);")
        self.lblAY.setObjectName("lblAY")
        self.horizontalLayout_5.addWidget(self.lblAY)
        self.gridLayout_9.addLayout(self.horizontalLayout_5, 0, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 1, 0, 1, 1)
        self.sbAP = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbAP.sizePolicy().hasHeightForWidth())
        self.sbAP.setSizePolicy(sizePolicy)
        self.sbAP.setDecimals(2)
        self.sbAP.setMaximum(1000000.0)
        self.sbAP.setObjectName("sbAP")
        self.gridLayout_9.addWidget(self.sbAP, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_12.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_12.setHorizontalSpacing(2)
        self.gridLayout_12.setVerticalSpacing(1)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnB = QtWidgets.QToolButton(self.groupBox_4)
        self.btnB.setMinimumSize(QtCore.QSize(64, 26))
        self.btnB.setStyleSheet("QToolButton {min-width: 30; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton[popupMode=\"1\"] { padding-right: 32px; }\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton:checked{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton::menu-button{border: 1px solid gray; border-top-right-radius: 6px; border-bottom-right-radius: 6px; width: 30px; }\n"
"QToolButton::menu-arrow:open {top: 1px; left: 1px;}")
        self.btnB.setText("")
        self.btnB.setCheckable(True)
        self.btnB.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.btnB.setObjectName("btnB")
        self.horizontalLayout_6.addWidget(self.btnB)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.lblBX = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBX.sizePolicy().hasHeightForWidth())
        self.lblBX.setSizePolicy(sizePolicy)
        self.lblBX.setStyleSheet("color: rgb(0, 0, 255);")
        self.lblBX.setObjectName("lblBX")
        self.horizontalLayout_6.addWidget(self.lblBX)
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_6.addWidget(self.label_20)
        self.lblBY = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblBY.sizePolicy().hasHeightForWidth())
        self.lblBY.setSizePolicy(sizePolicy)
        self.lblBY.setStyleSheet("color: rgb(0, 0, 255);")
        self.lblBY.setObjectName("lblBY")
        self.horizontalLayout_6.addWidget(self.lblBY)
        self.gridLayout_12.addLayout(self.horizontalLayout_6, 0, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.gridLayout_12.addWidget(self.label_13, 1, 0, 1, 1)
        self.sbBP = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.sbBP.setDecimals(2)
        self.sbBP.setMaximum(1000000.0)
        self.sbBP.setObjectName("sbBP")
        self.gridLayout_12.addWidget(self.sbBP, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.gbCalcPoint = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.gbCalcPoint.setObjectName("gbCalcPoint")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gbCalcPoint)
        self.horizontalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_15 = QtWidgets.QLabel(self.gbCalcPoint)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setStyleSheet("color: rgb(0, 120, 0);")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_3.addWidget(self.label_15)
        self.lblYP = QtWidgets.QLabel(self.gbCalcPoint)
        self.lblYP.setStyleSheet("color: rgb(0, 120, 0);")
        self.lblYP.setObjectName("lblYP")
        self.horizontalLayout_3.addWidget(self.lblYP)
        self.label_16 = QtWidgets.QLabel(self.gbCalcPoint)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setStyleSheet("color: rgb(0, 120, 0);")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_3.addWidget(self.label_16)
        self.lblXP = QtWidgets.QLabel(self.gbCalcPoint)
        self.lblXP.setStyleSheet("color: rgb(0, 120, 0);")
        self.lblXP.setObjectName("lblXP")
        self.horizontalLayout_3.addWidget(self.lblXP)
        self.verticalLayout_2.addWidget(self.gbCalcPoint)
        self.cmbMeasureMethod = QtWidgets.QComboBox(self.scrollAreaWidgetContents_4)
        self.cmbMeasureMethod.setEditable(False)
        self.cmbMeasureMethod.setObjectName("cmbMeasureMethod")
        self.cmbMeasureMethod.addItem("")
        self.cmbMeasureMethod.addItem("")
        self.verticalLayout_2.addWidget(self.cmbMeasureMethod)
        self.bAddCalcPoint = QtWidgets.QToolButton(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bAddCalcPoint.sizePolicy().hasHeightForWidth())
        self.bAddCalcPoint.setSizePolicy(sizePolicy)
        self.bAddCalcPoint.setMinimumSize(QtCore.QSize(32, 32))
        self.bAddCalcPoint.setStyleSheet("QToolButton {min-width: 30; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton[popupMode=\"1\"] { padding-right: 32px; }\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton::menu-button{border: 1px solid gray; border-top-right-radius: 6px; border-bottom-right-radius: 6px; width: 30px; }\n"
"QToolButton::menu-arrow:open {top: 1px; left: 1px;}")
        self.bAddCalcPoint.setObjectName("bAddCalcPoint")
        self.verticalLayout_2.addWidget(self.bAddCalcPoint)
        self.bClear = QtWidgets.QToolButton(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bClear.sizePolicy().hasHeightForWidth())
        self.bClear.setSizePolicy(sizePolicy)
        self.bClear.setMinimumSize(QtCore.QSize(32, 32))
        self.bClear.setStyleSheet("QToolButton {min-width: 30; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton[popupMode=\"1\"] { padding-right: 32px; }\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton::menu-button{border: 1px solid gray; border-top-right-radius: 6px; border-bottom-right-radius: 6px; width: 30px; }\n"
"QToolButton::menu-arrow:open {top: 1px; left: 1px;}")
        self.bClear.setObjectName("bClear")
        self.verticalLayout_2.addWidget(self.bClear)
        self.bReplace = QtWidgets.QToolButton(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bReplace.sizePolicy().hasHeightForWidth())
        self.bReplace.setSizePolicy(sizePolicy)
        self.bReplace.setMinimumSize(QtCore.QSize(32, 32))
        self.bReplace.setStyleSheet("QToolButton {min-width: 30; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton[popupMode=\"1\"] { padding-right: 32px; }\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton::menu-button{border: 1px solid gray; border-top-right-radius: 6px; border-bottom-right-radius: 6px; width: 30px; }\n"
"QToolButton::menu-arrow:open {top: 1px; left: 1px;}")
        self.bReplace.setObjectName("bReplace")
        self.verticalLayout_2.addWidget(self.bReplace)
        spacerItem3 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_5.addWidget(self.scrollArea_4)
        self.stack.addWidget(self.page_4)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setLineWidth(0)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 244, 507))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblCRS = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCRS.sizePolicy().hasHeightForWidth())
        self.lblCRS.setSizePolicy(sizePolicy)
        self.lblCRS.setObjectName("lblCRS")
        self.horizontalLayout_2.addWidget(self.lblCRS)
        self.cmbCRS = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCRS.sizePolicy().hasHeightForWidth())
        self.cmbCRS.setSizePolicy(sizePolicy)
        self.cmbCRS.setMinimumSize(QtCore.QSize(0, 26))
        self.cmbCRS.setEditable(False)
        self.cmbCRS.setObjectName("cmbCRS")
        self.cmbCRS.addItem("")
        self.cmbCRS.addItem("")
        self.cmbCRS.addItem("")
        self.cmbCRS.addItem("")
        self.cmbCRS.addItem("")
        self.horizontalLayout_2.addWidget(self.cmbCRS)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.cmbPorts = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.cmbPorts.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPorts.sizePolicy().hasHeightForWidth())
        self.cmbPorts.setSizePolicy(sizePolicy)
        self.cmbPorts.setMinimumSize(QtCore.QSize(0, 26))
        self.cmbPorts.setObjectName("cmbPorts")
        self.horizontalLayout_8.addWidget(self.cmbPorts)
        self.btnPorts = QtWidgets.QToolButton(self.scrollAreaWidgetContents_2)
        self.btnPorts.setMinimumSize(QtCore.QSize(26, 26))
        self.btnPorts.setObjectName("btnPorts")
        self.horizontalLayout_8.addWidget(self.btnPorts)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.gbPointAddMode = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.gbPointAddMode.setEnabled(True)
        self.gbPointAddMode.setObjectName("gbPointAddMode")
        self.gridLayout = QtWidgets.QGridLayout(self.gbPointAddMode)
        self.gridLayout.setContentsMargins(4, 2, 4, 2)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.rbTimeAverage = QtWidgets.QRadioButton(self.gbPointAddMode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbTimeAverage.sizePolicy().hasHeightForWidth())
        self.rbTimeAverage.setSizePolicy(sizePolicy)
        self.rbTimeAverage.setChecked(True)
        self.rbTimeAverage.setObjectName("rbTimeAverage")
        self.gridLayout.addWidget(self.rbTimeAverage, 0, 0, 1, 1)
        self.sbMeasureCount = QtWidgets.QSpinBox(self.gbPointAddMode)
        self.sbMeasureCount.setMinimum(1)
        self.sbMeasureCount.setMaximum(9999)
        self.sbMeasureCount.setProperty("value", 5)
        self.sbMeasureCount.setObjectName("sbMeasureCount")
        self.gridLayout.addWidget(self.sbMeasureCount, 0, 2, 1, 1)
        self.rbShotsAverage = QtWidgets.QRadioButton(self.gbPointAddMode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbShotsAverage.sizePolicy().hasHeightForWidth())
        self.rbShotsAverage.setSizePolicy(sizePolicy)
        self.rbShotsAverage.setObjectName("rbShotsAverage")
        self.gridLayout.addWidget(self.rbShotsAverage, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gbPointAddMode)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2)
        self.sbMeasureDistance = QtWidgets.QSpinBox(self.gbPointAddMode)
        self.sbMeasureDistance.setMinimum(1)
        self.sbMeasureDistance.setMaximum(999)
        self.sbMeasureDistance.setProperty("value", 25)
        self.sbMeasureDistance.setObjectName("sbMeasureDistance")
        self.gridLayout.addWidget(self.sbMeasureDistance, 1, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.gbPointAddMode)
        self.gbMarker = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.gbMarker.setCheckable(True)
        self.gbMarker.setObjectName("gbMarker")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gbMarker)
        self.gridLayout_6.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_6.setHorizontalSpacing(2)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_5 = QtWidgets.QLabel(self.gbMarker)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.cmbMarker = QtWidgets.QComboBox(self.gbMarker)
        self.cmbMarker.setObjectName("cmbMarker")
        self.gridLayout_6.addWidget(self.cmbMarker, 0, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.gbMarker)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 2, 0, 1, 1)
        self.sMarkerSize = QtWidgets.QSlider(self.gbMarker)
        self.sMarkerSize.setMinimum(8)
        self.sMarkerSize.setMaximum(128)
        self.sMarkerSize.setSingleStep(4)
        self.sMarkerSize.setPageStep(8)
        self.sMarkerSize.setSliderPosition(24)
        self.sMarkerSize.setOrientation(QtCore.Qt.Horizontal)
        self.sMarkerSize.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sMarkerSize.setTickInterval(8)
        self.sMarkerSize.setObjectName("sMarkerSize")
        self.gridLayout_6.addWidget(self.sMarkerSize, 2, 1, 1, 1)
        self.sbMarkerSize = QtWidgets.QSpinBox(self.gbMarker)
        self.sbMarkerSize.setMinimum(8)
        self.sbMarkerSize.setMaximum(128)
        self.sbMarkerSize.setProperty("value", 24)
        self.sbMarkerSize.setObjectName("sbMarkerSize")
        self.gridLayout_6.addWidget(self.sbMarkerSize, 2, 2, 1, 1)
        self.lblMarker = QtWidgets.QLabel(self.gbMarker)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMarker.sizePolicy().hasHeightForWidth())
        self.lblMarker.setSizePolicy(sizePolicy)
        self.lblMarker.setMaximumSize(QtCore.QSize(16777215, 130))
        self.lblMarker.setFrameShape(QtWidgets.QFrame.Box)
        self.lblMarker.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblMarker.setText("")
        self.lblMarker.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMarker.setObjectName("lblMarker")
        self.gridLayout_6.addWidget(self.lblMarker, 1, 0, 1, 3)
        self.verticalLayout_3.addWidget(self.gbMarker)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_8.setHorizontalSpacing(2)
        self.gridLayout_8.setVerticalSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.sbExt = QtWidgets.QSpinBox(self.groupBox_2)
        self.sbExt.setEnabled(False)
        self.sbExt.setMinimum(5)
        self.sbExt.setMaximum(100)
        self.sbExt.setProperty("value", 50)
        self.sbExt.setObjectName("sbExt")
        self.gridLayout_8.addWidget(self.sbExt, 1, 0, 1, 2)
        self.cmbCenter = QtWidgets.QComboBox(self.groupBox_2)
        self.cmbCenter.setObjectName("cmbCenter")
        self.cmbCenter.addItem("")
        self.cmbCenter.addItem("")
        self.cmbCenter.addItem("")
        self.gridLayout_8.addWidget(self.cmbCenter, 0, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.gbLogDir = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.gbLogDir.setObjectName("gbLogDir")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.gbLogDir)
        self.gridLayout_13.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_13.setHorizontalSpacing(2)
        self.gridLayout_13.setVerticalSpacing(1)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.eLogDir = QtWidgets.QLineEdit(self.gbLogDir)
        self.eLogDir.setMinimumSize(QtCore.QSize(0, 26))
        self.eLogDir.setObjectName("eLogDir")
        self.gridLayout_13.addWidget(self.eLogDir, 0, 1, 1, 1)
        self.cbLogGPS = QtWidgets.QCheckBox(self.gbLogDir)
        self.cbLogGPS.setObjectName("cbLogGPS")
        self.gridLayout_13.addWidget(self.cbLogGPS, 1, 1, 1, 2)
        self.btnChangeLogDir = QtWidgets.QToolButton(self.gbLogDir)
        self.btnChangeLogDir.setMinimumSize(QtCore.QSize(64, 26))
        self.btnChangeLogDir.setStyleSheet("QToolButton {min-width: 30; border: 1px solid #8f8f91; border-radius: 6px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #f6f7fa, stop: 1 #dadbde);}\n"
"QToolButton[popupMode=\"1\"] { padding-right: 32px; }\n"
"QToolButton:pressed{background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #dadbde, stop: 1 #f6f7fa);}\n"
"QToolButton::menu-button{border: 1px solid gray; border-top-right-radius: 6px; border-bottom-right-radius: 6px; width: 30px; }\n"
"QToolButton::menu-arrow:open {top: 1px; left: 1px;}")
        self.btnChangeLogDir.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.btnChangeLogDir.setObjectName("btnChangeLogDir")
        self.gridLayout_13.addWidget(self.btnChangeLogDir, 0, 2, 1, 1)
        self.cbSaveMeasure = QtWidgets.QCheckBox(self.gbLogDir)
        self.cbSaveMeasure.setChecked(True)
        self.cbSaveMeasure.setObjectName("cbSaveMeasure")
        self.gridLayout_13.addWidget(self.cbSaveMeasure, 2, 1, 1, 1)
        self.sbMesaureSaveTime = QtWidgets.QSpinBox(self.gbLogDir)
        self.sbMesaureSaveTime.setMinimum(1)
        self.sbMesaureSaveTime.setObjectName("sbMesaureSaveTime")
        self.gridLayout_13.addWidget(self.sbMesaureSaveTime, 2, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.gbLogDir)
        self.gbPointDistance = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.gbPointDistance.setCheckable(True)
        self.gbPointDistance.setChecked(False)
        self.gbPointDistance.setObjectName("gbPointDistance")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gbPointDistance)
        self.gridLayout_10.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_10.setHorizontalSpacing(2)
        self.gridLayout_10.setVerticalSpacing(1)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_18 = QtWidgets.QLabel(self.gbPointDistance)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gbPointDistance)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.gridLayout_10.addWidget(self.label_17, 2, 0, 1, 1)
        self.cmbFontSizes = QtWidgets.QComboBox(self.gbPointDistance)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFontSizes.sizePolicy().hasHeightForWidth())
        self.cmbFontSizes.setSizePolicy(sizePolicy)
        self.cmbFontSizes.setObjectName("cmbFontSizes")
        self.gridLayout_10.addWidget(self.cmbFontSizes, 2, 1, 1, 2)
        self.lblSampleText = QtWidgets.QLabel(self.gbPointDistance)
        self.lblSampleText.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSampleText.setFont(font)
        self.lblSampleText.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblSampleText.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblSampleText.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSampleText.setObjectName("lblSampleText")
        self.gridLayout_10.addWidget(self.lblSampleText, 4, 0, 1, 3)
        self.label_19 = QtWidgets.QLabel(self.gbPointDistance)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.gridLayout_10.addWidget(self.label_19, 3, 0, 1, 1)
        self.btnFontColor = QtWidgets.QPushButton(self.gbPointDistance)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFontColor.sizePolicy().hasHeightForWidth())
        self.btnFontColor.setSizePolicy(sizePolicy)
        self.btnFontColor.setObjectName("btnFontColor")
        self.gridLayout_10.addWidget(self.btnFontColor, 3, 1, 1, 2)
        self.cmbFonts = QtWidgets.QFontComboBox(self.gbPointDistance)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFonts.sizePolicy().hasHeightForWidth())
        self.cmbFonts.setSizePolicy(sizePolicy)
        self.cmbFonts.setEditable(False)
        self.cmbFonts.setFontFilters(QtWidgets.QFontComboBox.ScalableFonts)
        self.cmbFonts.setObjectName("cmbFonts")
        self.gridLayout_10.addWidget(self.cmbFonts, 1, 1, 1, 2)
        self.verticalLayout_3.addWidget(self.gbPointDistance)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sWidgetsSize = QtWidgets.QSlider(self.groupBox_3)
        self.sWidgetsSize.setMinimum(8)
        self.sWidgetsSize.setMaximum(48)
        self.sWidgetsSize.setSingleStep(4)
        self.sWidgetsSize.setPageStep(8)
        self.sWidgetsSize.setProperty("value", 20)
        self.sWidgetsSize.setSliderPosition(20)
        self.sWidgetsSize.setOrientation(QtCore.Qt.Horizontal)
        self.sWidgetsSize.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sWidgetsSize.setTickInterval(8)
        self.sWidgetsSize.setObjectName("sWidgetsSize")
        self.horizontalLayout.addWidget(self.sWidgetsSize)
        self.sbWidgetsSize = QtWidgets.QSpinBox(self.groupBox_3)
        self.sbWidgetsSize.setMinimum(8)
        self.sbWidgetsSize.setMaximum(48)
        self.sbWidgetsSize.setProperty("value", 20)
        self.sbWidgetsSize.setObjectName("sbWidgetsSize")
        self.horizontalLayout.addWidget(self.sbWidgetsSize)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_7.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.stack.addWidget(self.page)
        self.verticalLayout.addWidget(self.stack)
        self.stack.raise_()
        self.frame.raise_()
        GPSTracker.setWidget(self.dockWidgetContents)

        self.retranslateUi(GPSTracker)
        self.stack.setCurrentIndex(2)
        self.cmbCRS.setCurrentIndex(4)
        self.sMarkerSize.valueChanged['int'].connect(self.sbMarkerSize.setValue)
        self.sbMarkerSize.valueChanged['int'].connect(self.sMarkerSize.setValue)
        self.sWidgetsSize.valueChanged['int'].connect(self.sbWidgetsSize.setValue)
        self.sbWidgetsSize.valueChanged['int'].connect(self.sWidgetsSize.setValue)
        QtCore.QMetaObject.connectSlotsByName(GPSTracker)
        GPSTracker.setTabOrder(self.cmbCRS, self.scrollArea_3)
        GPSTracker.setTabOrder(self.scrollArea_3, self.scrollArea)
        GPSTracker.setTabOrder(self.scrollArea, self.cmbLayers)
        GPSTracker.setTabOrder(self.cmbLayers, self.scrollArea_2)
        GPSTracker.setTabOrder(self.scrollArea_2, self.gbMarker)
        GPSTracker.setTabOrder(self.gbMarker, self.cmbMarker)
        GPSTracker.setTabOrder(self.cmbMarker, self.sMarkerSize)
        GPSTracker.setTabOrder(self.sMarkerSize, self.sbMarkerSize)
        GPSTracker.setTabOrder(self.sbMarkerSize, self.sbExt)
        GPSTracker.setTabOrder(self.sbExt, self.gbPointDistance)
        GPSTracker.setTabOrder(self.gbPointDistance, self.cmbFonts)
        GPSTracker.setTabOrder(self.cmbFonts, self.cmbFontSizes)
        GPSTracker.setTabOrder(self.cmbFontSizes, self.btnFontColor)

    def retranslateUi(self, GPSTracker):
        _translate = QtCore.QCoreApplication.translate
        GPSTracker.setWindowTitle(_translate("GPSTracker", "GPS Tracker"))
        self.btnPosition.setToolTip(_translate("GPSTracker", "Położenie"))
        self.btnLayers.setToolTip(_translate("GPSTracker", "Rejestracja punktów"))
        self.btnCalcPoint.setToolTip(_translate("GPSTracker", "Wcięcie liniowe w przód"))
        self.btnOptions.setToolTip(_translate("GPSTracker", "Ustawienia"))
        self.btnConnect.setToolTip(_translate("GPSTracker", "Połączenie z odbiornikiem GPS"))
        self.btnConnect.setText(_translate("GPSTracker", "Połącz"))
        self.gbLayers.setTitle(_translate("GPSTracker", "Zapis obiektów"))
        self.btnAddFeatures.setText(_translate("GPSTracker", "Zap. wsz. pkt"))
        self.btnSelection.setText(_translate("GPSTracker", "Zaznacz wszystkie"))
        self.cbDisplayPoints.setText(_translate("GPSTracker", "Wyświetl punkty w oknie mapy"))
        self.btnMeasurePoint.setText(_translate("GPSTracker", "Nowy pomiar"))
        self.btnDeletePoint.setText(_translate("GPSTracker", "Usuń wybrany"))
        self.btnIntervalMeasure.setText(_translate("GPSTracker", "Automatyczny\n"
"pomiar co 25 m"))
        self.groupBox.setTitle(_translate("GPSTracker", "Punkt lewy A"))
        self.btnA.setAccessibleDescription(_translate("GPSTracker", "left"))
        self.label_4.setText(_translate("GPSTracker", "X:"))
        self.lblAX.setText(_translate("GPSTracker", "N/A"))
        self.label_8.setText(_translate("GPSTracker", "Y:"))
        self.lblAY.setText(_translate("GPSTracker", "N/A"))
        self.label_12.setText(_translate("GPSTracker", "Odległość AP:"))
        self.groupBox_4.setTitle(_translate("GPSTracker", "Punkt prawy B"))
        self.btnB.setAccessibleDescription(_translate("GPSTracker", "right"))
        self.label_9.setText(_translate("GPSTracker", "X:"))
        self.lblBX.setText(_translate("GPSTracker", "N/A"))
        self.label_20.setText(_translate("GPSTracker", "Y:"))
        self.lblBY.setText(_translate("GPSTracker", "N/A"))
        self.label_13.setText(_translate("GPSTracker", "Odległość BP:"))
        self.gbCalcPoint.setTitle(_translate("GPSTracker", "Szukany punkt P"))
        self.label_15.setText(_translate("GPSTracker", "X:"))
        self.lblYP.setText(_translate("GPSTracker", "N/A"))
        self.label_16.setText(_translate("GPSTracker", "Y:"))
        self.lblXP.setText(_translate("GPSTracker", "N/A"))
        self.cmbMeasureMethod.setItemText(0, _translate("GPSTracker", "Wcięcie liniowe"))
        self.cmbMeasureMethod.setItemText(1, _translate("GPSTracker", "Pomiar offsetowy"))
        self.bAddCalcPoint.setToolTip(_translate("GPSTracker", "Dodaj punkt P do listy"))
        self.bAddCalcPoint.setText(_translate("GPSTracker", "Dodaj punkt"))
        self.bClear.setToolTip(_translate("GPSTracker", "Zresetuj wprowadzone dane"))
        self.bClear.setText(_translate("GPSTracker", "Wyczyść dane"))
        self.bReplace.setToolTip(_translate("GPSTracker", "Zamień współrzędne punktów A i B"))
        self.bReplace.setText(_translate("GPSTracker", "Zamień punkt A i B"))
        self.lblCRS.setText(_translate("GPSTracker", "PUWG:"))
        self.cmbCRS.setToolTip(_translate("GPSTracker", "Układ współrzędnych w jakim wyświetlane są koordynaty punktów"))
        self.cmbCRS.setItemText(0, _translate("GPSTracker", "2000 Strefa 5"))
        self.cmbCRS.setItemText(1, _translate("GPSTracker", "2000 Strefa 6"))
        self.cmbCRS.setItemText(2, _translate("GPSTracker", "2000 Strefa 7"))
        self.cmbCRS.setItemText(3, _translate("GPSTracker", "2000 Strefa 8"))
        self.cmbCRS.setItemText(4, _translate("GPSTracker", "1992"))
        self.label_6.setText(_translate("GPSTracker", "Port:"))
        self.cmbPorts.setToolTip(_translate("GPSTracker", "Nazwa portu, do którego podłączony jest odbiornik GPS"))
        self.btnPorts.setToolTip(_translate("GPSTracker", "Odśwież listę portów"))
        self.gbPointAddMode.setTitle(_translate("GPSTracker", "Rejestracja punktów"))
        self.rbTimeAverage.setToolTip(_translate("GPSTracker", "Średni pomiar w określonym czasie"))
        self.rbTimeAverage.setText(_translate("GPSTracker", "Sek. /"))
        self.rbShotsAverage.setToolTip(_translate("GPSTracker", "Średnia z określonej liczby pomiarów"))
        self.rbShotsAverage.setText(_translate("GPSTracker", "L.pom."))
        self.label.setText(_translate("GPSTracker", "Odległość dla aut.pom."))
        self.sbMeasureDistance.setSuffix(_translate("GPSTracker", " m"))
        self.gbMarker.setTitle(_translate("GPSTracker", "Wskaźnik"))
        self.label_5.setText(_translate("GPSTracker", "Plik ikony:"))
        self.label_7.setText(_translate("GPSTracker", "Rozmiar:"))
        self.groupBox_2.setTitle(_translate("GPSTracker", "Centrowanie mapy"))
        self.sbExt.setSuffix(_translate("GPSTracker", "% zasięgu mapy"))
        self.cmbCenter.setItemText(0, _translate("GPSTracker", "zawsze"))
        self.cmbCenter.setItemText(1, _translate("GPSTracker", "nigdy"))
        self.cmbCenter.setItemText(2, _translate("GPSTracker", "przy wychodzeniu..."))
        self.gbLogDir.setTitle(_translate("GPSTracker", "Katalog logowania"))
        self.cbLogGPS.setText(_translate("GPSTracker", "Zapisuj informacje z GPS w formacie NMEA"))
        self.btnChangeLogDir.setText(_translate("GPSTracker", "..."))
        self.cbSaveMeasure.setText(_translate("GPSTracker", "Automatyczny zapis pomiarów:"))
        self.sbMesaureSaveTime.setSuffix(_translate("GPSTracker", " min"))
        self.gbPointDistance.setTitle(_translate("GPSTracker", "Odległość od punktu"))
        self.label_18.setText(_translate("GPSTracker", "Czcionka:"))
        self.label_17.setText(_translate("GPSTracker", "Rozmiar:"))
        self.lblSampleText.setText(_translate("GPSTracker", "123.45"))
        self.label_19.setText(_translate("GPSTracker", "Kolor:"))
        self.groupBox_3.setTitle(_translate("GPSTracker", "Rozmiar przycisków"))

